FROM python:3.11.6

WORKDIR /app

RUN apt-get update && \
    apt-get install -y sudo \
    vim \
    pip \
    default-jdk

ADD helpers /app/helpers
ADD drivers /app/drivers
ADD sql_scripts /app/sql_scripts

COPY app.py .env requirements.txt /app/

RUN pip install -r /app/requirements.txt


CMD ["python", "-u" ,"app.py"]